name: craigshaynak
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37208
title: Craig Ricci Shaynak
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0e3077'
    - '#744300'
    - '#ffb996'
    - '#000000'
  brandStrength: 0.1784805015195161
  lightness: 0.0625
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
