name: craigshaynak
favicon: null
layout_spectrum: 0.7827246831730008
typography_spectrum: 0.5666833291761577
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.1784805015195161
  lightness: 0.28179485304281116
  saturation: 0.08985394262708724
  rhythmicContrast: 0.7934127794578671
purpose: []
